spring:
  application:
    name: photo
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

cloud:
  aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET}