spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/photo
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug

cloud:
  aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${S3_BUCKET}
