spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/photo
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

cloud:
  aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET}
