spring:
  application:
    name: photo
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/photo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    user:
      name: user
      password: 1234
jwt:
  issuer: solball@naver.com
  secretKey: ourhood_secretKey